export const appModules = [
  {
    id: 'auth',
    title: '用户注册/登录',
    phase: 'v1',
    status: 'planned',
    dependencies: [],
    primaryRoutes: ['/auth', '/login', '/register'],
  },
  {
    id: 'pet-profile',
    title: '宠物档案',
    phase: 'v1',
    status: 'in-progress',
    dependencies: ['auth'],
    primaryRoutes: ['/pets', '/pets/new', '/pets/:petId'],
  },
  {
    id: 'recipes',
    title: '食谱',
    phase: 'v1',
    status: 'in-progress',
    dependencies: ['auth', 'pet-profile'],
    primaryRoutes: ['/recipes', '/recipes/:recipeId', '/recommendations'],
  },
  {
    id: 'fresh-food-making',
    title: '鲜食制作',
    phase: 'v1',
    status: 'in-progress',
    dependencies: ['auth', 'pet-profile', 'recipes', 'device-management'],
    primaryRoutes: ['/make', '/make/:recipeId', '/cooking'],
  },
  {
    id: 'commerce',
    title: '商城',
    phase: 'v2',
    status: 'planned',
    dependencies: ['auth', 'pet-profile', 'recipes'],
    primaryRoutes: ['/shop', '/cart', '/orders'],
  },
  {
    id: 'device-management',
    title: '设备管理',
    phase: 'v1',
    status: 'in-progress',
    dependencies: ['auth'],
    primaryRoutes: ['/devices', '/devices/add', '/devices/:deviceId'],
  },
  {
    id: 'health-tracking',
    title: '健康追踪',
    phase: 'v2',
    status: 'planned',
    dependencies: ['auth', 'pet-profile', 'recipes'],
    primaryRoutes: ['/health', '/health/logs', '/health/reports'],
  },
  {
    id: 'message-center',
    title: '消息中心',
    phase: 'v2',
    status: 'planned',
    dependencies: ['auth'],
    primaryRoutes: ['/messages', '/messages/:messageId'],
  },
  {
    id: 'account-settings',
    title: '账号设置',
    phase: 'v1',
    status: 'planned',
    dependencies: ['auth'],
    primaryRoutes: ['/account', '/account/settings', '/account/privacy'],
  },
];

export default appModules;
