const SUPPORTED_LOCALES = ['zh', 'en', 'de', 'fr', 'es', 'it', 'ja', 'ko'];

function template(title, reason, adjustment) {
  return Object.fromEntries(SUPPORTED_LOCALES.map((locale, index) => [
    locale,
    [title[index], reason[index], adjustment[index]],
  ]));
}

const FRESH_CHECK_FINDING_TEMPLATES = Object.freeze({
  PROFESSIONAL_CONFIRMATION_REQUIRED: template(
    ['需要专业确认', 'Professional confirmation required', 'Fachliche Bestätigung erforderlich', 'Confirmation professionnelle requise', 'Se requiere confirmación profesional', 'È necessaria una conferma professionale', '専門家の確認が必要です', '전문가 확인이 필요합니다'],
    ['当前宠物处于幼龄、特殊生理阶段或有健康记录，不能仅凭通用配方判断长期适宜性。', 'This pet is young, in a special physiological stage, or has recorded health conditions, so long-term suitability cannot be determined from a general recipe alone.', 'Dieses Tier ist jung, befindet sich in einer besonderen physiologischen Phase oder hat dokumentierte Gesundheitsprobleme; die Langzeiteignung kann daher nicht allein anhand einer allgemeinen Rezeptur beurteilt werden.', 'Cet animal est jeune, traverse une phase physiologique particulière ou présente des antécédents de santé ; une recette générale ne suffit donc pas à déterminer son adéquation à long terme.', 'La mascota es joven, está en una etapa fisiológica especial o tiene problemas de salud registrados; por tanto, una receta general no basta para determinar su idoneidad a largo plazo.', 'L’animale è giovane, si trova in una fase fisiologica particolare o presenta condizioni di salute registrate; una ricetta generica non basta quindi a stabilirne l’idoneità a lungo termine.', '幼齢、特別な生理段階、または健康上の記録があるため、一般的なレシピだけでは長期的な適合性を判断できません。', '어리거나 특수 생리 단계에 있거나 건강 기록이 있어 일반 배합만으로 장기 적합성을 판단할 수 없습니다.'],
    ['本次仅作结构检查；长期喂养前请由执业兽医或宠物营养专业人员确认。', 'Treat this as a structural check only; have a licensed veterinarian or qualified pet nutrition professional confirm the long-term plan.', 'Dies ist nur eine Strukturprüfung; lassen Sie den Langzeitplan vor der dauerhaften Fütterung tierärztlich oder ernährungsfachlich bestätigen.', 'Il s’agit uniquement d’un contrôle structurel ; faites confirmer le programme à long terme par un vétérinaire ou un professionnel qualifié en nutrition animale.', 'Esta es solo una revisión estructural; antes de una alimentación prolongada, solicite la confirmación de un veterinario o profesional cualificado en nutrición animal.', 'Questa è solo una verifica strutturale; prima dell’alimentazione a lungo termine, far confermare il piano da un veterinario o da un professionista qualificato in nutrizione animale.', '今回は構成上の確認のみです。長期給与前に獣医師または有資格のペット栄養専門家へ確認してください。', '이번 결과는 구조 점검에 한정됩니다. 장기 급여 전 수의사 또는 자격을 갖춘 반려동물 영양 전문가에게 확인하세요.'],
  ),
  PUPPY_TARGET_WEIGHT_CONFLICT: template(
    ['幼犬目标体重档案冲突', 'Puppy target-weight conflict', 'Konflikt beim Zielgewicht des Welpen', 'Conflit de poids cible chez le chiot', 'Conflicto con el peso objetivo del cachorro', 'Conflitto con il peso obiettivo del cucciolo', '子犬の目標体重に矛盾があります', '강아지 목표 체중 정보가 충돌합니다'],
    ['当前体重为{current_weight_kg}kg，但目标体重{target_weight_kg}kg更低；幼犬仍在生长，不能据此得出减重结论。', 'Current weight is {current_weight_kg} kg, but the target is lower at {target_weight_kg} kg. Because the puppy is still growing, this must not be interpreted as a weight-loss target.', 'Das aktuelle Gewicht beträgt {current_weight_kg} kg, das Zielgewicht liegt jedoch mit {target_weight_kg} kg darunter. Da der Welpe noch wächst, darf daraus kein Abnehmziel abgeleitet werden.', 'Le poids actuel est de {current_weight_kg} kg, alors que le poids cible est inférieur ({target_weight_kg} kg). Le chiot étant encore en croissance, cela ne doit pas être interprété comme un objectif d’amaigrissement.', 'El peso actual es de {current_weight_kg} kg, pero el objetivo es inferior ({target_weight_kg} kg). Como el cachorro sigue creciendo, no debe interpretarse como un objetivo de pérdida de peso.', 'Il peso attuale è {current_weight_kg} kg, mentre l’obiettivo è inferiore ({target_weight_kg} kg). Poiché il cucciolo è ancora in crescita, non va interpretato come obiettivo di dimagrimento.', '現在体重は{current_weight_kg}kgですが、目標体重はそれより低い{target_weight_kg}kgです。成長中の子犬では減量目標として扱えません。', '현재 체중은 {current_weight_kg}kg이지만 목표 체중은 더 낮은 {target_weight_kg}kg입니다. 성장 중인 강아지이므로 감량 목표로 해석하면 안 됩니다.'],
    ['暂停使用该目标体重进行减重计算；结合BCS、生长曲线和连续称重复核目标。', 'Do not use this target for weight-loss calculations. Reassess it using BCS, the growth curve, and serial weight measurements.', 'Verwenden Sie dieses Zielgewicht nicht für Abnehmberechnungen. Prüfen Sie es anhand von BCS, Wachstumskurve und regelmäßigen Gewichtsmessungen.', 'N’utilisez pas ce poids cible pour calculer une perte de poids. Réévaluez-le à l’aide du BCS, de la courbe de croissance et de pesées répétées.', 'No use este objetivo para calcular una pérdida de peso. Revíselo mediante BCS, curva de crecimiento y controles de peso sucesivos.', 'Non usare questo obiettivo per calcolare il dimagrimento. Rivalutarlo con BCS, curva di crescita e pesate seriali.', 'この目標体重を減量計算に使用せず、BCS、成長曲線、継続的な体重測定で再評価してください。', '이 목표 체중을 감량 계산에 사용하지 말고 BCS, 성장 곡선, 연속 체중 측정으로 다시 평가하세요.'],
  ),
  LOW_ANIMAL_PROTEIN: template(
    ['动物性食材占比较低', 'Low proportion of animal ingredients', 'Niedriger Anteil tierischer Zutaten', 'Faible proportion d’ingrédients animaux', 'Proporción baja de ingredientes animales', 'Bassa proporzione di ingredienti animali', '動物性食材の割合が低めです', '동물성 식재료 비율이 낮습니다'],
    ['动物性食材占配方{actual_pct}%，低于{minimum_pct}%。', 'Animal ingredients make up {actual_pct}% of the recipe, below {minimum_pct}%.', 'Tierische Zutaten machen {actual_pct}% der Rezeptur aus und liegen damit unter {minimum_pct}%.', 'Les ingrédients animaux représentent {actual_pct}% de la recette, soit moins de {minimum_pct}%.', 'Los ingredientes animales representan el {actual_pct}% de la receta, por debajo del {minimum_pct}%.', 'Gli ingredienti animali costituiscono il {actual_pct}% della ricetta, sotto il {minimum_pct}%.', '動物性食材は配合の{actual_pct}%で、{minimum_pct}%を下回っています。', '동물성 식재료가 배합의 {actual_pct}%로 {minimum_pct}%보다 낮습니다.'],
    ['重点复核蛋白质、脂肪、必需氨基酸和能量密度，并提高适配的动物性食材比例。', 'Review protein, fat, essential amino acids, and energy density, and increase suitable animal ingredients as needed.', 'Prüfen Sie Protein, Fett, essenzielle Aminosäuren und Energiedichte und erhöhen Sie bei Bedarf geeignete tierische Zutaten.', 'Vérifiez les protéines, les lipides, les acides aminés essentiels et la densité énergétique, puis augmentez si nécessaire les ingrédients animaux adaptés.', 'Revise proteínas, grasas, aminoácidos esenciales y densidad energética, y aumente los ingredientes animales adecuados cuando sea necesario.', 'Verificare proteine, grassi, amminoacidi essenziali e densità energetica e aumentare, se necessario, gli ingredienti animali adatti.', 'たんぱく質、脂質、必須アミノ酸、エネルギー密度を確認し、必要に応じて適切な動物性食材を増やしてください。', '단백질·지방·필수 아미노산·에너지 밀도를 확인하고 필요하면 적합한 동물성 식재료 비율을 높이세요.'],
  ),
  ANIMAL_PROTEIN_ACCEPTABLE_REVIEW: template(
    ['动物性食材处于可接受区间', 'Animal ingredients are within the acceptable range', 'Tierische Zutaten liegen im akzeptablen Bereich', 'Les ingrédients animaux sont dans la plage acceptable', 'Los ingredientes animales están dentro del intervalo aceptable', 'Gli ingredienti animali rientrano nell’intervallo accettabile', '動物性食材は許容範囲内です', '동물성 식재료가 허용 범위에 있습니다'],
    ['动物性食材占配方{actual_pct}%，处于{minimum_pct}%–{recommended_minimum_pct}%的可接受区间。', 'Animal ingredients make up {actual_pct}% of the recipe, within the acceptable {minimum_pct}%–{recommended_minimum_pct}% range.', 'Tierische Zutaten machen {actual_pct}% der Rezeptur aus und liegen im akzeptablen Bereich von {minimum_pct}% bis {recommended_minimum_pct}%.', 'Les ingrédients animaux représentent {actual_pct}% de la recette, dans la plage acceptable de {minimum_pct}% à {recommended_minimum_pct}%.', 'Los ingredientes animales representan el {actual_pct}% de la receta, dentro del intervalo aceptable del {minimum_pct}% al {recommended_minimum_pct}%.', 'Gli ingredienti animali costituiscono il {actual_pct}% della ricetta, nell’intervallo accettabile tra {minimum_pct}% e {recommended_minimum_pct}%.', '動物性食材は配合の{actual_pct}%で、許容範囲の{minimum_pct}%～{recommended_minimum_pct}%に入っています。', '동물성 식재료가 배합의 {actual_pct}%로 허용 범위인 {minimum_pct}%~{recommended_minimum_pct}%에 있습니다.'],
    ['通过营养计算确认蛋白质、脂肪、必需氨基酸和能量密度是否满足当前宠物需求。', 'Confirm through nutrition calculations that protein, fat, essential amino acids, and energy density meet this pet’s needs.', 'Bestätigen Sie rechnerisch, dass Protein, Fett, essenzielle Aminosäuren und Energiedichte den Bedarf dieses Tieres decken.', 'Confirmez par le calcul nutritionnel que les protéines, les lipides, les acides aminés essentiels et la densité énergétique répondent aux besoins de cet animal.', 'Confirme mediante cálculos nutricionales que las proteínas, grasas, aminoácidos esenciales y densidad energética cubren las necesidades de esta mascota.', 'Confermare con i calcoli nutrizionali che proteine, grassi, amminoacidi essenziali e densità energetica soddisfino i fabbisogni dell’animale.', '栄養計算により、たんぱく質、脂質、必須アミノ酸、エネルギー密度が現在の必要量を満たすか確認してください。', '영양 계산으로 단백질·지방·필수 아미노산·에너지 밀도가 현재 반려견의 필요량을 충족하는지 확인하세요.'],
  ),
  HIGH_ANIMAL_PROTEIN_REVIEW: template(
    ['高动物性食材结构', 'High-animal-ingredient structure', 'Rezeptur mit hohem Anteil tierischer Zutaten', 'Structure riche en ingrédients animaux', 'Estructura con alta proporción de ingredientes animales', 'Struttura ad alto contenuto di ingredienti animali', '動物性食材が多い構成です', '동물성 식재료 비율이 높은 구성입니다'],
    ['动物性食材占配方{actual_pct}%，处于{high_range_minimum_pct}%–{maximum_pct}%的较高区间。', 'Animal ingredients make up {actual_pct}% of the recipe, within the high range of {high_range_minimum_pct}%–{maximum_pct}%.', 'Tierische Zutaten machen {actual_pct}% der Rezeptur aus und liegen im hohen Bereich von {high_range_minimum_pct}% bis {maximum_pct}%.', 'Les ingrédients animaux représentent {actual_pct}% de la recette, dans la plage élevée de {high_range_minimum_pct}% à {maximum_pct}%.', 'Los ingredientes animales representan el {actual_pct}% de la receta, dentro del intervalo alto del {high_range_minimum_pct}% al {maximum_pct}%.', 'Gli ingredienti animali costituiscono il {actual_pct}% della ricetta, nell’intervallo elevato tra {high_range_minimum_pct}% e {maximum_pct}%.', '動物性食材は配合の{actual_pct}%で、{high_range_minimum_pct}%～{maximum_pct}%の高めの範囲です。', '동물성 식재료가 배합의 {actual_pct}%로 높은 범위인 {high_range_minimum_pct}%~{maximum_pct}%에 있습니다.'],
    ['这不一定有问题，但应复核脂肪、钙磷、内脏比例和总能量。', 'This is not necessarily a problem, but fat, calcium-phosphorus balance, organ proportion, and total energy should be reviewed.', 'Dies ist nicht zwangsläufig problematisch; Fett, Kalzium-Phosphor-Verhältnis, Innereienanteil und Gesamtenergie sollten jedoch geprüft werden.', 'Ce n’est pas nécessairement problématique, mais il faut vérifier les lipides, l’équilibre calcium-phosphore, la proportion d’abats et l’énergie totale.', 'No es necesariamente un problema, pero deben revisarse la grasa, el equilibrio calcio-fósforo, la proporción de vísceras y la energía total.', 'Non è necessariamente un problema, ma vanno verificati grassi, equilibrio calcio-fosforo, proporzione di frattaglie ed energia totale.', '必ずしも問題ではありませんが、脂質、カルシウムとリン、内臓の割合、総エネルギーを確認してください。', '반드시 문제인 것은 아니지만 지방, 칼슘·인 균형, 내장 비율, 총에너지를 확인해야 합니다.'],
  ),
  EXCESSIVE_ANIMAL_PROTEIN: template(
    ['动物性食材占比过高', 'Excessive proportion of animal ingredients', 'Zu hoher Anteil tierischer Zutaten', 'Proportion excessive d’ingrédients animaux', 'Proporción excesiva de ingredientes animales', 'Proporzione eccessiva di ingredienti animali', '動物性食材の割合が高すぎます', '동물성 식재료 비율이 지나치게 높습니다'],
    ['动物性食材占配方{actual_pct}%，超过{maximum_pct}%；高比例本身不能自动视为健康。', 'Animal ingredients make up {actual_pct}% of the recipe, above {maximum_pct}%. A high proportion alone must not be assumed to be healthy.', 'Tierische Zutaten machen {actual_pct}% der Rezeptur aus und überschreiten {maximum_pct}%. Ein hoher Anteil ist nicht automatisch gesund.', 'Les ingrédients animaux représentent {actual_pct}% de la recette, au-dessus de {maximum_pct}%. Une proportion élevée n’est pas automatiquement synonyme d’équilibre.', 'Los ingredientes animales representan el {actual_pct}% de la receta, por encima del {maximum_pct}%. Una proporción alta no implica por sí sola que la receta sea saludable.', 'Gli ingredienti animali costituiscono il {actual_pct}% della ricetta, oltre il {maximum_pct}%. Una quota elevata non è automaticamente salutare.', '動物性食材は配合の{actual_pct}%で、{maximum_pct}%を超えています。割合が高いだけで健康的とは判断できません。', '동물성 식재료가 배합의 {actual_pct}%로 {maximum_pct}%를 넘습니다. 비율이 높다는 이유만으로 건강하다고 판단할 수 없습니다.'],
    ['检查纤维来源是否被挤压，并复核脂肪、磷、铜、维生素A和总能量。', 'Check whether fibre sources have been displaced, and review fat, phosphorus, copper, vitamin A, and total energy.', 'Prüfen Sie, ob Ballaststoffquellen verdrängt wurden, und kontrollieren Sie Fett, Phosphor, Kupfer, Vitamin A und Gesamtenergie.', 'Vérifiez si les sources de fibres ont été évincées, ainsi que les lipides, le phosphore, le cuivre, la vitamine A et l’énergie totale.', 'Compruebe si se han desplazado las fuentes de fibra y revise grasa, fósforo, cobre, vitamina A y energía total.', 'Verificare se le fonti di fibra sono state ridotte e controllare grassi, fosforo, rame, vitamina A ed energia totale.', '食物繊維源が不足していないか確認し、脂質、リン、銅、ビタミンA、総エネルギーを再評価してください。', '섬유 공급원이 밀려나지 않았는지 확인하고 지방·인·구리·비타민 A·총에너지를 재검토하세요.'],
  ),
  LOW_CARB_FORMULA: template(
    ['低碳水配方', 'Low-carbohydrate recipe', 'Kohlenhydratarme Rezeptur', 'Recette pauvre en glucides', 'Receta baja en carbohidratos', 'Ricetta a basso contenuto di carboidrati', '低炭水化物の配合です', '저탄수화물 배합입니다'],
    ['淀粉类碳水食材占配方{actual_pct}%，低于{low_threshold_pct}%。', 'Starchy carbohydrate ingredients make up {actual_pct}% of the recipe, below {low_threshold_pct}%.', 'Stärkehaltige Kohlenhydrate machen {actual_pct}% der Rezeptur aus und liegen unter {low_threshold_pct}%.', 'Les glucides féculents représentent {actual_pct}% de la recette, soit moins de {low_threshold_pct}%.', 'Los carbohidratos con almidón representan el {actual_pct}% de la receta, por debajo del {low_threshold_pct}%.', 'I carboidrati amidacei costituiscono il {actual_pct}% della ricetta, sotto il {low_threshold_pct}%.', 'でんぷん質炭水化物は配合の{actual_pct}%で、{low_threshold_pct}%未満です。', '전분성 탄수화물이 배합의 {actual_pct}%로 {low_threshold_pct}%보다 낮습니다.'],
    ['标记为低碳水配方，并确认脂肪、蛋白质和总能量能够满足需求。', 'Treat this as a low-carbohydrate recipe and confirm that fat, protein, and total energy meet requirements.', 'Kennzeichnen Sie die Rezeptur als kohlenhydratarm und bestätigen Sie, dass Fett, Protein und Gesamtenergie den Bedarf decken.', 'Considérez cette recette comme pauvre en glucides et vérifiez que les lipides, les protéines et l’énergie totale couvrent les besoins.', 'Considérela una receta baja en carbohidratos y confirme que la grasa, la proteína y la energía total cubren las necesidades.', 'Considerarla una ricetta a basso contenuto di carboidrati e verificare che grassi, proteine ed energia totale coprano i fabbisogni.', '低炭水化物配合として扱い、脂質、たんぱく質、総エネルギーが必要量を満たすか確認してください。', '저탄수화물 배합으로 분류하고 지방·단백질·총에너지가 필요량을 충족하는지 확인하세요.'],
  ),
  LOW_CARB: template(
    ['碳水比例偏低', 'Carbohydrate proportion is low', 'Niedriger Kohlenhydratanteil', 'Proportion de glucides faible', 'Proporción de carbohidratos baja', 'Proporzione di carboidrati bassa', '炭水化物の割合が低めです', '탄수화물 비율이 낮습니다'],
    ['淀粉类碳水食材占配方{actual_pct}%，低于建议值{recommended_minimum_pct}%。', 'Starchy carbohydrate ingredients make up {actual_pct}% of the recipe, below the suggested {recommended_minimum_pct}%.', 'Stärkehaltige Kohlenhydrate machen {actual_pct}% der Rezeptur aus und liegen unter dem Richtwert von {recommended_minimum_pct}%.', 'Les glucides féculents représentent {actual_pct}% de la recette, sous la valeur conseillée de {recommended_minimum_pct}%.', 'Los carbohidratos con almidón representan el {actual_pct}% de la receta, por debajo del {recommended_minimum_pct}% recomendado.', 'I carboidrati amidacei costituiscono il {actual_pct}% della ricetta, sotto il valore consigliato del {recommended_minimum_pct}%.', 'でんぷん質炭水化物は配合の{actual_pct}%で、推奨値{recommended_minimum_pct}%を下回っています。', '전분성 탄수화물이 배합의 {actual_pct}%로 권장치 {recommended_minimum_pct}%보다 낮습니다.'],
    ['结合活动量、脂肪来源和总能量确认长期适用性。', 'Assess long-term suitability together with activity level, fat sources, and total energy.', 'Beurteilen Sie die Langzeiteignung zusammen mit Aktivitätsniveau, Fettquellen und Gesamtenergie.', 'Évaluez l’adéquation à long terme en tenant compte de l’activité, des sources de lipides et de l’énergie totale.', 'Evalúe la idoneidad a largo plazo junto con el nivel de actividad, las fuentes de grasa y la energía total.', 'Valutare l’idoneità a lungo termine considerando attività, fonti di grassi ed energia totale.', '活動量、脂質源、総エネルギーと合わせて長期的な適合性を確認してください。', '활동량, 지방 공급원, 총에너지와 함께 장기 적합성을 확인하세요.'],
  ),
  HIGH_CARB: template(
    ['碳水比例偏高', 'Carbohydrate proportion is high', 'Hoher Kohlenhydratanteil', 'Proportion de glucides élevée', 'Proporción de carbohidratos alta', 'Proporzione di carboidrati elevata', '炭水化物の割合が高めです', '탄수화물 비율이 높습니다'],
    ['淀粉类碳水食材占配方{actual_pct}%，超过参考上限{maximum_pct}%。', 'Starchy carbohydrate ingredients make up {actual_pct}% of the recipe, above the {maximum_pct}% reference limit.', 'Stärkehaltige Kohlenhydrate machen {actual_pct}% der Rezeptur aus und überschreiten den Richtwert von {maximum_pct}%.', 'Les glucides féculents représentent {actual_pct}% de la recette, au-dessus de la limite de référence de {maximum_pct}%.', 'Los carbohidratos con almidón representan el {actual_pct}% de la receta, por encima del límite de referencia del {maximum_pct}%.', 'I carboidrati amidacei costituiscono il {actual_pct}% della ricetta, oltre il limite di riferimento del {maximum_pct}%.', 'でんぷん質炭水化物は配合の{actual_pct}%で、目安上限{maximum_pct}%を超えています。', '전분성 탄수화물이 배합의 {actual_pct}%로 기준 상한 {maximum_pct}%를 넘습니다.'],
    ['检查蛋白质密度和总能量，并在需要时减少淀粉类碳水。', 'Review protein density and total energy, and reduce starchy carbohydrates if needed.', 'Prüfen Sie Proteindichte und Gesamtenergie und reduzieren Sie bei Bedarf stärkehaltige Kohlenhydrate.', 'Vérifiez la densité protéique et l’énergie totale, puis réduisez les glucides féculents si nécessaire.', 'Revise la densidad proteica y la energía total, y reduzca los carbohidratos con almidón si es necesario.', 'Verificare densità proteica ed energia totale e ridurre, se necessario, i carboidrati amidacei.', 'たんぱく質密度と総エネルギーを確認し、必要に応じてでんぷん質炭水化物を減らしてください。', '단백질 밀도와 총에너지를 확인하고 필요하면 전분성 탄수화물을 줄이세요.'],
  ),
  VERY_HIGH_CARB: template(
    ['碳水比例超过常规上限', 'Carbohydrate proportion exceeds the routine limit', 'Kohlenhydratanteil überschreitet den üblichen Grenzwert', 'La proportion de glucides dépasse la limite habituelle', 'La proporción de carbohidratos supera el límite habitual', 'La proporzione di carboidrati supera il limite abituale', '炭水化物が通常の上限を超えています', '탄수화물 비율이 일반 상한을 넘습니다'],
    ['淀粉类碳水食材占配方{actual_pct}%，超过{maximum_pct}%，不建议作为常规犬鲜食结构。', 'Starchy carbohydrate ingredients make up {actual_pct}% of the recipe, above {maximum_pct}%, and are not recommended as a routine fresh-food structure for dogs.', 'Stärkehaltige Kohlenhydrate machen {actual_pct}% der Rezeptur aus und überschreiten {maximum_pct}%; dies wird nicht als übliche Frischfutterstruktur für Hunde empfohlen.', 'Les glucides féculents représentent {actual_pct}% de la recette, au-dessus de {maximum_pct}% ; cette structure n’est pas recommandée comme alimentation fraîche habituelle du chien.', 'Los carbohidratos con almidón representan el {actual_pct}% de la receta, por encima del {maximum_pct}%, y no se recomiendan como estructura habitual de alimentación fresca canina.', 'I carboidrati amidacei costituiscono il {actual_pct}% della ricetta, oltre il {maximum_pct}%, e non sono consigliati come struttura abituale di alimentazione fresca per cani.', 'でんぷん質炭水化物は配合の{actual_pct}%で、{maximum_pct}%を超えており、犬の日常的な手作り食構成として推奨されません。', '전분성 탄수화물이 배합의 {actual_pct}%로 {maximum_pct}%를 넘어 일반적인 반려견 신선식 구성으로 권장되지 않습니다.'],
    ['减少淀粉类碳水，避免稀释动物性营养，并重新核算蛋白质密度和总能量。', 'Reduce starchy carbohydrates to avoid displacing animal-source nutrients, then recalculate protein density and total energy.', 'Reduzieren Sie stärkehaltige Kohlenhydrate, damit tierische Nährstoffquellen nicht verdrängt werden, und berechnen Sie Proteindichte und Gesamtenergie neu.', 'Réduisez les glucides féculents pour ne pas évincer les nutriments d’origine animale, puis recalculez la densité protéique et l’énergie totale.', 'Reduzca los carbohidratos con almidón para no desplazar nutrientes de origen animal y vuelva a calcular la densidad proteica y la energía total.', 'Ridurre i carboidrati amidacei per non sostituire i nutrienti di origine animale, quindi ricalcolare densità proteica ed energia totale.', 'でんぷん質炭水化物を減らして動物性栄養源を圧迫しないようにし、たんぱく質密度と総エネルギーを再計算してください。', '전분성 탄수화물을 줄여 동물성 영양 공급원이 밀려나지 않게 하고 단백질 밀도와 총에너지를 다시 계산하세요.'],
  ),
  LOW_NON_STARCHY_PRODUCE: template(
    ['非淀粉果蔬比例偏低', 'Low proportion of non-starchy produce', 'Niedriger Anteil nicht stärkehaltiger Pflanzenkost', 'Faible proportion de végétaux non féculents', 'Proporción baja de vegetales no feculentos', 'Bassa proporzione di vegetali non amidacei', '非でんぷん質の野菜・果物が少なめです', '비전분 과채 비율이 낮습니다'],
    ['非淀粉果蔬占配方{actual_pct}%。', 'Non-starchy fruit and vegetables make up {actual_pct}% of the recipe.', 'Nicht stärkehaltiges Obst und Gemüse machen {actual_pct}% der Rezeptur aus.', 'Les fruits et légumes non féculents représentent {actual_pct}% de la recette.', 'Las frutas y verduras sin almidón representan el {actual_pct}% de la receta.', 'Frutta e verdura non amidacee costituiscono il {actual_pct}% della ricetta.', '非でんぷん質の野菜・果物は配合の{actual_pct}%です。', '비전분 과채가 배합의 {actual_pct}%입니다.'],
    ['结合实际纤维含量、食材多样性和粪便情况，确认是否需要增加低淀粉蔬菜。', 'Use actual fibre content, ingredient variety, and stool quality to decide whether more low-starch vegetables are needed.', 'Beurteilen Sie anhand des tatsächlichen Ballaststoffgehalts, der Zutatenvielfalt und der Kotqualität, ob mehr stärkearmes Gemüse nötig ist.', 'Tenez compte de la teneur réelle en fibres, de la diversité des ingrédients et de la qualité des selles pour décider s’il faut davantage de légumes pauvres en amidon.', 'Considere el contenido real de fibra, la variedad de ingredientes y la calidad de las heces para decidir si se necesitan más verduras bajas en almidón.', 'Valutare il contenuto reale di fibre, la varietà degli ingredienti e la qualità delle feci per stabilire se servano più verdure a basso amido.', '実際の食物繊維量、食材の多様性、便の状態から、低でんぷん野菜を増やす必要があるか判断してください。', '실제 섬유 함량, 식재료 다양성, 변 상태를 바탕으로 저전분 채소를 늘릴지 판단하세요.'],
  ),
  HIGH_VEGETABLE: template(
    ['非淀粉果蔬比例偏高', 'High proportion of non-starchy produce', 'Hoher Anteil nicht stärkehaltiger Pflanzenkost', 'Proportion élevée de végétaux non féculents', 'Proporción alta de vegetales no feculentos', 'Alta proporzione di vegetali non amidacei', '非でんぷん質の野菜・果物が多めです', '비전분 과채 비율이 높습니다'],
    ['非淀粉果蔬占配方{actual_pct}%，超过参考上限{maximum_pct}%。', 'Non-starchy fruit and vegetables make up {actual_pct}% of the recipe, above the {maximum_pct}% reference limit.', 'Nicht stärkehaltiges Obst und Gemüse machen {actual_pct}% der Rezeptur aus und überschreiten den Richtwert von {maximum_pct}%.', 'Les fruits et légumes non féculents représentent {actual_pct}% de la recette, au-dessus de la limite de référence de {maximum_pct}%.', 'Las frutas y verduras sin almidón representan el {actual_pct}% de la receta, por encima del límite de referencia del {maximum_pct}%.', 'Frutta e verdura non amidacee costituiscono il {actual_pct}% della ricetta, oltre il limite di riferimento del {maximum_pct}%.', '非でんぷん質の野菜・果物は配合の{actual_pct}%で、目安上限{maximum_pct}%を超えています。', '비전분 과채가 배합의 {actual_pct}%로 기준 상한 {maximum_pct}%를 넘습니다.'],
    ['检查能量密度和粪便情况，并避免挤占动物性营养来源。', 'Review energy density and stool quality, and avoid displacing animal-source nutrients.', 'Prüfen Sie Energiedichte und Kotqualität und vermeiden Sie eine Verdrängung tierischer Nährstoffquellen.', 'Vérifiez la densité énergétique et la qualité des selles, sans évincer les nutriments d’origine animale.', 'Revise la densidad energética y la calidad de las heces, y evite desplazar nutrientes de origen animal.', 'Verificare densità energetica e qualità delle feci, evitando di sostituire i nutrienti di origine animale.', 'エネルギー密度と便の状態を確認し、動物性栄養源を圧迫しないようにしてください。', '에너지 밀도와 변 상태를 확인하고 동물성 영양 공급원이 밀려나지 않게 하세요.'],
  ),
  VERY_HIGH_VEGETABLE: template(
    ['非淀粉果蔬比例过高', 'Excessive proportion of non-starchy produce', 'Zu hoher Anteil nicht stärkehaltiger Pflanzenkost', 'Proportion excessive de végétaux non féculents', 'Proporción excesiva de vegetales no feculentos', 'Proporzione eccessiva di vegetali non amidacei', '非でんぷん質の野菜・果物が多すぎます', '비전분 과채 비율이 지나치게 높습니다'],
    ['非淀粉果蔬占配方{actual_pct}%，超过{maximum_pct}%，可能导致食量过大、能量密度下降和纤维过多。', 'Non-starchy fruit and vegetables make up {actual_pct}% of the recipe, above {maximum_pct}%, which may increase food volume, lower energy density, and provide excessive fibre.', 'Nicht stärkehaltiges Obst und Gemüse machen {actual_pct}% der Rezeptur aus und überschreiten {maximum_pct}%; dies kann Futtervolumen und Ballaststoffe erhöhen und die Energiedichte senken.', 'Les fruits et légumes non féculents représentent {actual_pct}% de la recette, au-dessus de {maximum_pct}%, ce qui peut augmenter le volume alimentaire, réduire la densité énergétique et apporter trop de fibres.', 'Las frutas y verduras sin almidón representan el {actual_pct}% de la receta, por encima del {maximum_pct}%, lo que puede aumentar el volumen, reducir la densidad energética y aportar demasiada fibra.', 'Frutta e verdura non amidacee costituiscono il {actual_pct}% della ricetta, oltre il {maximum_pct}%, con possibile aumento del volume, riduzione della densità energetica ed eccesso di fibre.', '非でんぷん質の野菜・果物は配合の{actual_pct}%で、{maximum_pct}%を超えています。食事量の増加、エネルギー密度の低下、食物繊維過多につながる可能性があります。', '비전분 과채가 배합의 {actual_pct}%로 {maximum_pct}%를 넘어 식사량 증가, 에너지 밀도 저하, 섬유 과다로 이어질 수 있습니다.'],
    ['减少果蔬总量，并重新核算食量、能量密度和纤维水平。', 'Reduce the total produce amount and recalculate food volume, energy density, and fibre level.', 'Reduzieren Sie die Pflanzenmenge und berechnen Sie Futtervolumen, Energiedichte und Ballaststoffgehalt neu.', 'Réduisez la quantité totale de végétaux et recalculez le volume alimentaire, la densité énergétique et le niveau de fibres.', 'Reduzca la cantidad total de vegetales y vuelva a calcular el volumen, la densidad energética y el nivel de fibra.', 'Ridurre la quantità totale di vegetali e ricalcolare volume, densità energetica e livello di fibre.', '野菜・果物の総量を減らし、食事量、エネルギー密度、食物繊維量を再計算してください。', '과채 총량을 줄이고 식사량, 에너지 밀도, 섬유 수준을 다시 계산하세요.'],
  ),
  HIGH_FRUIT: template(
    ['水果比例偏高', 'Fruit proportion is high', 'Hoher Obstanteil', 'Proportion de fruits élevée', 'Proporción de fruta alta', 'Proporzione di frutta elevata', '果物の割合が高めです', '과일 비율이 높습니다'],
    ['水果占配方{actual_pct}%，超过建议上限{maximum_pct}%。', 'Fruit makes up {actual_pct}% of the recipe, above the suggested maximum of {maximum_pct}%.', 'Obst macht {actual_pct}% der Rezeptur aus und überschreitet den empfohlenen Höchstwert von {maximum_pct}%.', 'Les fruits représentent {actual_pct}% de la recette, au-dessus du maximum conseillé de {maximum_pct}%.', 'La fruta representa el {actual_pct}% de la receta, por encima del máximo recomendado del {maximum_pct}%.', 'La frutta costituisce il {actual_pct}% della ricetta, oltre il massimo consigliato del {maximum_pct}%.', '果物は配合の{actual_pct}%で、推奨上限{maximum_pct}%を超えています。', '과일이 배합의 {actual_pct}%로 권장 상한 {maximum_pct}%를 넘습니다.'],
    ['减少高糖水果，使主要果蔬来源回到低淀粉蔬菜。', 'Reduce high-sugar fruit so that low-starch vegetables remain the main produce source.', 'Reduzieren Sie zuckerreiches Obst, damit stärkearmes Gemüse die wichtigste pflanzliche Quelle bleibt.', 'Réduisez les fruits riches en sucre afin que les légumes pauvres en amidon restent la principale source végétale.', 'Reduzca la fruta con alto contenido de azúcar para que las verduras bajas en almidón sigan siendo la principal fuente vegetal.', 'Ridurre la frutta ricca di zuccheri affinché le verdure a basso amido restino la principale fonte vegetale.', '糖分の多い果物を減らし、低でんぷん野菜を主な野菜・果物源にしてください。', '당분이 높은 과일을 줄여 저전분 채소가 주요 과채 공급원이 되게 하세요.'],
  ),
  LOW_FAT_SOURCE: template(
    ['脂肪来源不足', 'Insufficient fat source', 'Unzureichende Fettquelle', 'Source de lipides insuffisante', 'Fuente de grasa insuficiente', 'Fonte di grassi insufficiente', '脂質源が不足しています', '지방 공급원이 부족합니다'],
    ['估算脂肪为{actual_g_per_1000kcal}g/1000kcal，低于阶段参考最低值{minimum_g_per_1000kcal}g/1000kcal，且没有明确脂肪来源。', 'Estimated fat is {actual_g_per_1000kcal} g/1000 kcal, below the stage minimum of {minimum_g_per_1000kcal} g/1000 kcal, with no explicit fat source identified.', 'Der geschätzte Fettgehalt beträgt {actual_g_per_1000kcal} g/1000 kcal und liegt unter dem Mindestwert von {minimum_g_per_1000kcal} g/1000 kcal; eine klare Fettquelle fehlt.', 'Les lipides estimés sont de {actual_g_per_1000kcal} g/1000 kcal, sous le minimum de {minimum_g_per_1000kcal} g/1000 kcal pour ce stade, sans source de lipides clairement identifiée.', 'La grasa estimada es de {actual_g_per_1000kcal} g/1000 kcal, por debajo del mínimo de {minimum_g_per_1000kcal} g/1000 kcal para esta etapa, sin una fuente explícita de grasa.', 'I grassi stimati sono {actual_g_per_1000kcal} g/1000 kcal, sotto il minimo di fase di {minimum_g_per_1000kcal} g/1000 kcal, senza una fonte di grassi esplicita.', '推定脂質は{actual_g_per_1000kcal}g/1000kcalで、段階別最低値{minimum_g_per_1000kcal}g/1000kcalを下回り、明確な脂質源もありません。', '추정 지방은 {actual_g_per_1000kcal}g/1000kcal로 단계별 최저 기준 {minimum_g_per_1000kcal}g/1000kcal보다 낮고 명확한 지방 공급원도 없습니다.'],
    ['专业确认后加入适配的脂肪来源，并重新核算总能量和必需脂肪酸。', 'After professional confirmation, add a suitable fat source and recalculate total energy and essential fatty acids.', 'Ergänzen Sie nach fachlicher Bestätigung eine geeignete Fettquelle und berechnen Sie Gesamtenergie und essenzielle Fettsäuren neu.', 'Après confirmation professionnelle, ajoutez une source de lipides adaptée et recalculez l’énergie totale et les acides gras essentiels.', 'Tras la confirmación profesional, añada una fuente de grasa adecuada y vuelva a calcular la energía total y los ácidos grasos esenciales.', 'Dopo conferma professionale, aggiungere una fonte di grassi adatta e ricalcolare energia totale e acidi grassi essenziali.', '専門家の確認後に適切な脂質源を追加し、総エネルギーと必須脂肪酸を再計算してください。', '전문가 확인 후 적합한 지방 공급원을 추가하고 총에너지와 필수 지방산을 다시 계산하세요.'],
  ),
  MACRO_DATA_INCOMPLETE: template(
    ['宏量营养估算不完整', 'Macronutrient estimate is incomplete', 'Makronährstoffschätzung unvollständig', 'Estimation des macronutriments incomplète', 'Estimación de macronutrientes incompleta', 'Stima dei macronutrienti incompleta', '主要栄養素の推定が不完全です', '다량영양소 추정이 불완전합니다'],
    ['营养数据仅覆盖{coverage_weight_pct}%的食材重量，无法可靠判断蛋白质、脂肪和碳水是否达标。', 'Nutrition data covers only {coverage_weight_pct}% of ingredient weight, so protein, fat, and carbohydrate adequacy cannot be assessed reliably.', 'Nährwertdaten decken nur {coverage_weight_pct}% des Zutatengewichts ab; Protein, Fett und Kohlenhydrate können daher nicht zuverlässig beurteilt werden.', 'Les données nutritionnelles ne couvrent que {coverage_weight_pct}% du poids des ingrédients ; l’adéquation des protéines, lipides et glucides ne peut donc pas être évaluée de façon fiable.', 'Los datos nutricionales solo cubren el {coverage_weight_pct}% del peso de los ingredientes, por lo que no puede evaluarse con fiabilidad la adecuación de proteínas, grasas y carbohidratos.', 'I dati nutrizionali coprono solo il {coverage_weight_pct}% del peso degli ingredienti; non è quindi possibile valutare con affidabilità proteine, grassi e carboidrati.', '栄養データは食材重量の{coverage_weight_pct}%しかカバーしておらず、たんぱく質、脂質、炭水化物の充足度を正確に判断できません。', '영양 데이터가 식재료 중량의 {coverage_weight_pct}%만 포함해 단백질·지방·탄수화물 충족 여부를 신뢰성 있게 판단할 수 없습니다.'],
    ['补充未识别食材的生熟状态或营养标签后重新验证。', 'Add the raw/cooked state or nutrition label for unresolved ingredients, then run the check again.', 'Ergänzen Sie Roh- oder Garzustand bzw. Nährwertangaben der ungeklärten Zutaten und prüfen Sie erneut.', 'Précisez l’état cru ou cuit ou l’étiquette nutritionnelle des ingrédients non résolus, puis relancez la vérification.', 'Añada el estado crudo o cocido o la etiqueta nutricional de los ingredientes no resueltos y vuelva a comprobar.', 'Aggiungere lo stato crudo o cotto o l’etichetta nutrizionale degli ingredienti non risolti, quindi ripetere la verifica.', '未確認食材の生・加熱状態または栄養表示を追加して再確認してください。', '확인되지 않은 식재료의 생식·조리 상태 또는 영양 표시를 추가한 뒤 다시 검사하세요.'],
  ),
  INGREDIENT_NUTRITION_UNAVAILABLE: template(
    ['食材营养值未取得', 'Ingredient nutrition data unavailable', 'Nährwertdaten der Zutat nicht verfügbar', 'Données nutritionnelles de l’ingrédient indisponibles', 'Datos nutricionales del ingrediente no disponibles', 'Dati nutrizionali dell’ingrediente non disponibili', '食材の栄養値を取得できません', '식재료 영양값을 확인할 수 없습니다'],
    ['{ingredient_name}经{lookup_attempts}次查询仍未返回有效营养值，未计入营养计算。', 'No valid nutrition values were returned for {ingredient_name} after {lookup_attempts} checks, so it was excluded from the nutrition calculation.', 'Für {ingredient_name} wurden nach {lookup_attempts} Abfragen keine gültigen Nährwerte gefunden; die Zutat wurde daher nicht in die Nährwertberechnung einbezogen.', 'Aucune valeur nutritionnelle valide n’a été obtenue pour {ingredient_name} après {lookup_attempts} vérifications ; cet ingrédient n’a donc pas été inclus dans le calcul nutritionnel.', 'No se obtuvieron valores nutricionales válidos para {ingredient_name} tras {lookup_attempts} consultas, por lo que se excluyó del cálculo nutricional.', 'Dopo {lookup_attempts} verifiche non sono stati ottenuti valori nutrizionali validi per {ingredient_name}; l’ingrediente è stato quindi escluso dal calcolo nutrizionale.', '{ingredient_name}は{lookup_attempts}回確認しても有効な栄養値が得られなかったため、栄養計算から除外されています。', '{ingredient_name}은(는) {lookup_attempts}회 조회 후에도 유효한 영양값이 없어 영양 계산에서 제외되었습니다.'],
    ['补充准确名称、部位、生熟状态或包装营养标签后重新验证。', 'Provide the exact name, cut, raw/cooked state, or package nutrition label, then check again.', 'Geben Sie genaue Bezeichnung, Teilstück, Roh- oder Garzustand bzw. die Nährwertkennzeichnung an und prüfen Sie erneut.', 'Précisez le nom exact, le morceau, l’état cru ou cuit ou l’étiquette nutritionnelle, puis vérifiez de nouveau.', 'Indique el nombre exacto, el corte, si está crudo o cocido o la etiqueta nutricional y vuelva a comprobar.', 'Indicare nome esatto, taglio, stato crudo o cotto o etichetta nutrizionale, quindi verificare di nuovo.', '正確な名称、部位、生・加熱状態、または製品の栄養表示を追加して再確認してください。', '정확한 명칭, 부위, 생식·조리 상태 또는 포장 영양 표시를 추가한 뒤 다시 검사하세요.'],
  ),
  ESSENTIAL_FATTY_ACID_SOURCE_MISSING: template(
    ['必需脂肪酸来源待确认', 'Essential fatty-acid source needs confirmation', 'Quelle essenzieller Fettsäuren muss bestätigt werden', 'Source d’acides gras essentiels à confirmer', 'Debe confirmarse la fuente de ácidos grasos esenciales', 'Fonte di acidi grassi essenziali da confermare', '必須脂肪酸源の確認が必要です', '필수 지방산 공급원 확인이 필요합니다'],
    ['未识别到明确的必需脂肪酸来源，当前全价营养包说明中也未确认Omega-3、鱼油或藻油。', 'No clear essential fatty-acid source was identified, and the complete nutrition pack does not confirm Omega-3, fish oil, or algal oil.', 'Es wurde keine eindeutige Quelle essenzieller Fettsäuren erkannt; auch Omega-3, Fischöl oder Algenöl sind in der Beschreibung des Vollnährstoffpakets nicht bestätigt.', 'Aucune source claire d’acides gras essentiels n’a été identifiée, et le pack nutritionnel complet ne confirme ni oméga-3, ni huile de poisson, ni huile d’algues.', 'No se identificó una fuente clara de ácidos grasos esenciales y el pack nutricional completo no confirma omega-3, aceite de pescado ni aceite de algas.', 'Non è stata identificata una fonte chiara di acidi grassi essenziali e il pack nutrizionale completo non conferma Omega-3, olio di pesce o olio di alghe.', '明確な必須脂肪酸源が確認できず、総合栄養パックの説明にもOmega-3、魚油、藻類油の記載が確認できません。', '명확한 필수 지방산 공급원이 확인되지 않았고 완전 영양 팩 설명에도 Omega-3, 어유 또는 조류유가 확인되지 않습니다.'],
    ['选择明确包含必需脂肪酸的全价营养包，或在专业建议下补充适配来源。', 'Choose a complete nutrition pack that clearly provides essential fatty acids, or add a suitable source under professional guidance.', 'Wählen Sie ein Vollnährstoffpaket mit klar ausgewiesenen essenziellen Fettsäuren oder ergänzen Sie unter fachlicher Anleitung eine geeignete Quelle.', 'Choisissez un pack nutritionnel complet apportant clairement des acides gras essentiels, ou ajoutez une source adaptée sur conseil professionnel.', 'Elija un pack nutricional completo que aporte claramente ácidos grasos esenciales o añada una fuente adecuada bajo supervisión profesional.', 'Scegliere un pack nutrizionale completo che fornisca chiaramente acidi grassi essenziali o aggiungere una fonte adatta sotto guida professionale.', '必須脂肪酸を明示した総合栄養パックを選ぶか、専門家の助言のもとで適切な供給源を追加してください。', '필수 지방산이 명확히 포함된 완전 영양 팩을 선택하거나 전문가 지도 아래 적합한 공급원을 추가하세요.'],
  ),
  B_PACK_APPLIED: template(
    ['必配全价营养包已纳入方案', 'Required complete nutrition pack included', 'Erforderliches Vollnährstoffpaket berücksichtigt', 'Pack nutritionnel complet requis inclus', 'Pack nutricional completo obligatorio incluido', 'Pack nutrizionale completo obbligatorio incluso', '必須の総合栄養パックを反映しました', '필수 완전 영양 팩이 반영되었습니다'],
    ['已按数据库说明识别营养包覆盖项目；剂量为每100g食材{grams_per_100g}g，烹饪完成后拌入，不计入食材比例、宏量营养、能量或烹饪参数。', 'The pack coverage was identified from the database instructions. Use {grams_per_100g} g per 100 g of ingredients and mix it in after cooking; it is excluded from ingredient ratios, macronutrients, energy, and cooking parameters.', 'Die Abdeckung des Pakets wurde anhand der Datenbankangaben ermittelt. Verwenden Sie {grams_per_100g} g je 100 g Zutaten und mischen Sie es nach dem Garen ein; es zählt nicht zu Zutatenverhältnissen, Makronährstoffen, Energie oder Garparametern.', 'La couverture du pack a été déterminée selon les indications de la base de données. Utilisez {grams_per_100g} g pour 100 g d’ingrédients et incorporez-le après cuisson ; il n’entre pas dans les proportions, macronutriments, énergie ou paramètres de cuisson.', 'La cobertura del pack se determinó según las instrucciones de la base de datos. Use {grams_per_100g} g por cada 100 g de ingredientes y mézclelo después de cocinar; no se incluye en proporciones, macronutrientes, energía ni parámetros de cocción.', 'La copertura del pack è stata determinata dalle indicazioni del database. Usare {grams_per_100g} g ogni 100 g di ingredienti e mescolare dopo la cottura; non rientra in proporzioni, macronutrienti, energia o parametri di cottura.', 'データベースの説明に基づいて栄養パックの補完項目を確認しました。食材100g当たり{grams_per_100g}gを加熱後に混ぜ、食材比率、主要栄養素、エネルギー、調理条件には算入しません。', '데이터베이스 설명에 따라 영양 팩 보완 항목을 확인했습니다. 식재료 100g당 {grams_per_100g}g을 조리 후 섞으며 식재료 비율, 다량영양소, 에너지, 조리 조건에는 포함하지 않습니다.'],
    ['标注剂量在烹饪完成后拌入，并继续处理仍存在的结构和能量问题。', 'Mix in the labelled dose after cooking and continue addressing any remaining structure or energy issues.', 'Mischen Sie die angegebene Dosis nach dem Garen ein und bearbeiten Sie verbleibende Struktur- oder Energieprobleme.', 'Incorporez la dose indiquée après cuisson et corrigez les éventuels problèmes de structure ou d’énergie restants.', 'Mezcle la dosis indicada después de cocinar y siga corrigiendo los problemas restantes de estructura o energía.', 'Mescolare la dose indicata dopo la cottura e correggere gli eventuali problemi residui di struttura o energia.', '表示された用量を加熱後に混ぜ、残っている構成やエネルギーの問題にも対応してください。', '표시 용량을 조리 후 섞고 남아 있는 구조 또는 에너지 문제도 계속 조정하세요.'],
  ),
  ENERGY_DENSITY_INCOMPLETE: template(
    ['部分食材的能量密度待确认', 'Energy density is incomplete for some ingredients', 'Energiedichte einiger Zutaten ist unvollständig', 'Densité énergétique incomplète pour certains ingrédients', 'Densidad energética incompleta para algunos ingredientes', 'Densità energetica incompleta per alcuni ingredienti', '一部食材のエネルギー密度が未確認です', '일부 식재료의 에너지 밀도가 확인되지 않았습니다'],
    ['{ingredient_names}暂无可靠能量数据；当前总能量仅为基于其余食材的保守下限。', 'Reliable energy data is unavailable for {ingredient_names}; the current total is a conservative lower bound based on the remaining ingredients.', 'Für {ingredient_names} liegen keine verlässlichen Energiedaten vor; die aktuelle Gesamtsumme ist nur eine konservative Untergrenze auf Basis der übrigen Zutaten.', 'Aucune donnée énergétique fiable n’est disponible pour {ingredient_names} ; le total actuel est une limite inférieure prudente calculée à partir des autres ingrédients.', 'No hay datos energéticos fiables para {ingredient_names}; el total actual es un límite inferior conservador basado en los demás ingredientes.', 'Non sono disponibili dati energetici affidabili per {ingredient_names}; il totale attuale è un limite inferiore prudenziale basato sugli altri ingredienti.', '{ingredient_names}の信頼できるエネルギーデータがないため、現在の総エネルギーは他の食材だけに基づく控えめな下限値です。', '{ingredient_names}의 신뢰할 수 있는 에너지 데이터가 없어 현재 총에너지는 나머지 식재료만 반영한 보수적 하한값입니다.'],
    ['补充生熟状态或包装营养标签后重新验证。', 'Provide the raw/cooked state or package nutrition label, then check again.', 'Ergänzen Sie Roh- oder Garzustand bzw. die Nährwertkennzeichnung und prüfen Sie erneut.', 'Précisez l’état cru ou cuit ou l’étiquette nutritionnelle, puis vérifiez de nouveau.', 'Indique el estado crudo o cocido o la etiqueta nutricional y vuelva a comprobar.', 'Indicare lo stato crudo o cotto o l’etichetta nutrizionale, quindi verificare di nuovo.', '生・加熱状態または製品の栄養表示を追加して再確認してください。', '생식·조리 상태 또는 포장 영양 표시를 추가한 뒤 다시 검사하세요.'],
  ),
  RECIPE_WEIGHT_TOO_LOW: template(
    ['食谱总量过低', 'Recipe amount is very low', 'Rezeptmenge ist sehr gering', 'Quantité de recette très faible', 'Cantidad de receta muy baja', 'Quantità della ricetta molto bassa', 'レシピ総量が少なすぎます', '레시피 총량이 매우 적습니다'],
    ['当前总重量为{total_weight_g}g，低于{minimum_weight_g}g，可能更接近零食或试吃量。', 'The current total is {total_weight_g} g, below {minimum_weight_g} g, and may be closer to a treat or tasting portion.', 'Die Gesamtmenge beträgt {total_weight_g} g und liegt unter {minimum_weight_g} g; sie entspricht möglicherweise eher einem Snack oder einer Probierportion.', 'La quantité totale est de {total_weight_g} g, sous {minimum_weight_g} g, et peut correspondre davantage à une friandise ou une portion d’essai.', 'La cantidad total es de {total_weight_g} g, por debajo de {minimum_weight_g} g, y puede corresponder más a un premio o una ración de prueba.', 'La quantità totale è {total_weight_g} g, sotto {minimum_weight_g} g, e può corrispondere più a uno snack o a una porzione di prova.', '総重量は{total_weight_g}gで、{minimum_weight_g}g未満です。おやつまたは試食量に近い可能性があります。', '현재 총중량이 {total_weight_g}g으로 {minimum_weight_g}g보다 적어 간식 또는 시험 급여량에 가까울 수 있습니다.'],
    ['确认食谱用途及其占每日总能量的比例。', 'Confirm the intended use of the recipe and its share of total daily energy.', 'Bestätigen Sie den Verwendungszweck und den Anteil an der täglichen Gesamtenergie.', 'Confirmez l’usage prévu de la recette et sa part dans l’énergie quotidienne totale.', 'Confirme el uso previsto de la receta y su proporción de la energía diaria total.', 'Confermare l’uso previsto della ricetta e la sua quota dell’energia giornaliera totale.', 'レシピの用途と、1日の総エネルギーに占める割合を確認してください。', '레시피 용도와 일일 총에너지에서 차지하는 비율을 확인하세요.'],
  ),
  MISSING_WEIGHT: template(
    ['缺少体重数据', 'Body weight is missing', 'Körpergewicht fehlt', 'Poids corporel manquant', 'Falta el peso corporal', 'Peso corporeo mancante', '体重データがありません', '체중 정보가 없습니다'],
    ['没有有效体重，无法计算每日能量需求。', 'A valid body weight is required to calculate daily energy requirements.', 'Für die Berechnung des täglichen Energiebedarfs ist ein gültiges Körpergewicht erforderlich.', 'Un poids corporel valide est nécessaire pour calculer les besoins énergétiques quotidiens.', 'Se necesita un peso corporal válido para calcular las necesidades energéticas diarias.', 'Per calcolare il fabbisogno energetico giornaliero è necessario un peso corporeo valido.', '1日のエネルギー必要量を計算するには有効な体重が必要です。', '일일 에너지 필요량을 계산하려면 유효한 체중이 필요합니다.'],
    ['补充当前体重后重新验证。', 'Enter the current body weight and run the check again.', 'Tragen Sie das aktuelle Körpergewicht ein und prüfen Sie erneut.', 'Renseignez le poids actuel puis relancez la vérification.', 'Introduzca el peso actual y vuelva a comprobar.', 'Inserire il peso attuale e ripetere la verifica.', '現在体重を入力して再確認してください。', '현재 체중을 입력한 뒤 다시 검사하세요.'],
  ),
  MISSING_ENERGY_SOURCE: template(
    ['无法可靠计算食谱能量', 'Recipe energy cannot be calculated reliably', 'Rezeptenergie kann nicht zuverlässig berechnet werden', 'Énergie de la recette impossible à calculer fiablement', 'No se puede calcular con fiabilidad la energía de la receta', 'Impossibile calcolare con affidabilità l’energia della ricetta', 'レシピのエネルギーを正確に計算できません', '레시피 에너지를 신뢰성 있게 계산할 수 없습니다'],
    ['当前食材缺少可用的能量数据，无法评估每日能量是否满足需求。', 'Usable energy data is missing for the current ingredients, so daily energy adequacy cannot be assessed.', 'Für die aktuellen Zutaten fehlen verwertbare Energiedaten; die Deckung des täglichen Energiebedarfs kann daher nicht beurteilt werden.', 'Les ingrédients actuels ne disposent pas de données énergétiques utilisables ; la couverture des besoins quotidiens ne peut donc pas être évaluée.', 'Faltan datos energéticos utilizables para los ingredientes actuales, por lo que no puede evaluarse si se cubren las necesidades diarias.', 'Mancano dati energetici utilizzabili per gli ingredienti attuali; non è quindi possibile valutare la copertura del fabbisogno giornaliero.', '現在の食材に利用可能なエネルギーデータがなく、1日の必要量を満たすか評価できません。', '현재 식재료에 사용할 수 있는 에너지 데이터가 없어 일일 필요량 충족 여부를 평가할 수 없습니다.'],
    ['补充准确食材信息或营养标签后重新验证。', 'Provide exact ingredient information or nutrition labels, then check again.', 'Ergänzen Sie genaue Zutatenangaben oder Nährwertkennzeichnungen und prüfen Sie erneut.', 'Ajoutez des informations précises sur les ingrédients ou les étiquettes nutritionnelles, puis vérifiez de nouveau.', 'Añada información exacta de los ingredientes o etiquetas nutricionales y vuelva a comprobar.', 'Aggiungere informazioni precise sugli ingredienti o etichette nutrizionali, quindi verificare di nuovo.', '正確な食材情報または栄養表示を追加して再確認してください。', '정확한 식재료 정보 또는 영양 표시를 추가한 뒤 다시 검사하세요.'],
  ),
  EXCESSIVE_DAILY_FOOD_VOLUME: template(
    ['每日食量过大，当前方案难以执行', 'Daily food volume is too high to be practical', 'Tägliche Futtermenge ist praktisch zu hoch', 'Volume alimentaire quotidien difficilement réalisable', 'Volumen diario de comida poco viable', 'Volume alimentare giornaliero poco praticabile', '1日の食事量が多すぎて実行が困難です', '일일 급여량이 너무 많아 실행하기 어렵습니다'],
    ['当前需约{daily_food_weight_g}g/日，占体重{daily_food_weight_pct_body_weight}%（每餐约{grams_per_meal}g），比阶段参考上限{reference_max_daily_grams}g高{exceeds_reference_by_pct}%。', 'The current plan requires about {daily_food_weight_g} g/day, {daily_food_weight_pct_body_weight}% of body weight ({grams_per_meal} g per meal), which is {exceeds_reference_by_pct}% above the stage reference maximum of {reference_max_daily_grams} g.', 'Der aktuelle Plan erfordert etwa {daily_food_weight_g} g/Tag bzw. {daily_food_weight_pct_body_weight}% des Körpergewichts ({grams_per_meal} g je Mahlzeit) und liegt {exceeds_reference_by_pct}% über dem Referenzmaximum von {reference_max_daily_grams} g.', 'Le plan actuel nécessite environ {daily_food_weight_g} g/jour, soit {daily_food_weight_pct_body_weight}% du poids corporel ({grams_per_meal} g par repas), ce qui dépasse de {exceeds_reference_by_pct}% le maximum de référence de {reference_max_daily_grams} g.', 'El plan actual requiere unos {daily_food_weight_g} g/día, el {daily_food_weight_pct_body_weight}% del peso corporal ({grams_per_meal} g por comida), un {exceeds_reference_by_pct}% por encima del máximo de referencia de {reference_max_daily_grams} g.', 'Il piano attuale richiede circa {daily_food_weight_g} g/giorno, pari al {daily_food_weight_pct_body_weight}% del peso corporeo ({grams_per_meal} g per pasto), il {exceeds_reference_by_pct}% oltre il massimo di riferimento di {reference_max_daily_grams} g.', '現在の計画では1日約{daily_food_weight_g}g、体重の{daily_food_weight_pct_body_weight}%（1食約{grams_per_meal}g）が必要で、段階別目安上限{reference_max_daily_grams}gを{exceeds_reference_by_pct}%上回ります。', '현재 계획은 하루 약 {daily_food_weight_g}g, 체중의 {daily_food_weight_pct_body_weight}%(1회 약 {grams_per_meal}g)가 필요하며 단계별 기준 상한 {reference_max_daily_grams}g보다 {exceeds_reference_by_pct}% 많습니다.'],
    ['提高适配的能量密度或调整配方结构，使每日总量回到可执行范围后重新验证。', 'Increase suitable energy density or adjust the recipe structure, then check again once the daily amount is practical.', 'Erhöhen Sie die geeignete Energiedichte oder passen Sie die Rezeptur an und prüfen Sie erneut, sobald die Tagesmenge praktikabel ist.', 'Augmentez de façon adaptée la densité énergétique ou ajustez la structure, puis vérifiez de nouveau lorsque la quantité quotidienne devient réalisable.', 'Aumente de forma adecuada la densidad energética o ajuste la estructura y vuelva a comprobar cuando la cantidad diaria sea viable.', 'Aumentare in modo appropriato la densità energetica o modificare la struttura, quindi verificare di nuovo quando la quantità giornaliera è praticabile.', '適切にエネルギー密度を高めるか配合構成を調整し、1日量が実行可能な範囲になってから再確認してください。', '적합하게 에너지 밀도를 높이거나 배합 구조를 조정해 일일 총량이 실행 가능한 범위가 되면 다시 검사하세요.'],
  ),
  DAILY_ENERGY_HIGH: template(
    ['每日能量偏高', 'Daily energy is high', 'Tagesenergie ist zu hoch', 'Énergie quotidienne élevée', 'Energía diaria alta', 'Energia giornaliera elevata', '1日のエネルギー量が高めです', '일일 에너지가 높습니다'],
    ['当前食谱约{total_kcal}kcal，高于建议范围{min_kcal}–{max_kcal}kcal。', 'The recipe provides about {total_kcal} kcal, above the suggested range of {min_kcal}–{max_kcal} kcal.', 'Die Rezeptur liefert etwa {total_kcal} kcal und liegt über dem empfohlenen Bereich von {min_kcal}–{max_kcal} kcal.', 'La recette fournit environ {total_kcal} kcal, au-dessus de la plage conseillée de {min_kcal} à {max_kcal} kcal.', 'La receta aporta unas {total_kcal} kcal, por encima del intervalo recomendado de {min_kcal} a {max_kcal} kcal.', 'La ricetta fornisce circa {total_kcal} kcal, oltre l’intervallo consigliato di {min_kcal}–{max_kcal} kcal.', '現在のレシピは約{total_kcal}kcalで、推奨範囲{min_kcal}～{max_kcal}kcalを上回っています。', '현재 레시피는 약 {total_kcal}kcal로 권장 범위 {min_kcal}~{max_kcal}kcal보다 높습니다.'],
    ['优先等比例调整主蛋白和碳水总量，不要仅删除钙源或必需脂肪酸来源。', 'Reduce the main protein and carbohydrate amounts proportionally; do not remove only calcium or essential fatty-acid sources.', 'Reduzieren Sie Hauptprotein und Kohlenhydrate proportional; entfernen Sie nicht nur Kalzium- oder essenzielle Fettsäurequellen.', 'Réduisez proportionnellement les principales sources de protéines et de glucides ; ne retirez pas uniquement le calcium ou les acides gras essentiels.', 'Reduzca proporcionalmente las principales fuentes de proteína y carbohidratos; no elimine solo las fuentes de calcio o ácidos grasos esenciales.', 'Ridurre proporzionalmente le principali fonti di proteine e carboidrati; non eliminare soltanto le fonti di calcio o acidi grassi essenziali.', '主なたんぱく源と炭水化物を同じ比率で減らし、カルシウム源や必須脂肪酸源だけを除かないでください。', '주 단백질과 탄수화물 양을 비례해서 줄이고 칼슘 또는 필수 지방산 공급원만 제거하지 마세요.'],
  ),
  DAILY_ENERGY_LOW: template(
    ['每日能量偏低', 'Daily energy is low', 'Tagesenergie ist zu niedrig', 'Énergie quotidienne faible', 'Energía diaria baja', 'Energia giornaliera bassa', '1日のエネルギー量が低めです', '일일 에너지가 낮습니다'],
    ['当前食谱约{total_kcal}kcal，低于建议范围{min_kcal}–{max_kcal}kcal，距离目标约差{gap_kcal}kcal。', 'The recipe provides about {total_kcal} kcal, below the suggested range of {min_kcal}–{max_kcal} kcal and about {gap_kcal} kcal short of the target.', 'Die Rezeptur liefert etwa {total_kcal} kcal, liegt unter dem empfohlenen Bereich von {min_kcal}–{max_kcal} kcal und etwa {gap_kcal} kcal unter dem Ziel.', 'La recette fournit environ {total_kcal} kcal, sous la plage conseillée de {min_kcal} à {max_kcal} kcal, avec un déficit d’environ {gap_kcal} kcal.', 'La receta aporta unas {total_kcal} kcal, por debajo del intervalo recomendado de {min_kcal} a {max_kcal} kcal, con un déficit aproximado de {gap_kcal} kcal.', 'La ricetta fornisce circa {total_kcal} kcal, sotto l’intervallo consigliato di {min_kcal}–{max_kcal} kcal, con un deficit di circa {gap_kcal} kcal.', '現在のレシピは約{total_kcal}kcalで、推奨範囲{min_kcal}～{max_kcal}kcalを下回り、目標まで約{gap_kcal}kcal不足しています。', '현재 레시피는 약 {total_kcal}kcal로 권장 범위 {min_kcal}~{max_kcal}kcal보다 낮고 목표보다 약 {gap_kcal}kcal 부족합니다.'],
    ['在保持配方结构的同时用适配食材补足能量，并重新验证总量与营养平衡。', 'Add energy with suitable ingredients while preserving the recipe structure, then recheck total amount and nutritional balance.', 'Ergänzen Sie Energie mit geeigneten Zutaten unter Erhalt der Rezeptstruktur und prüfen Sie Gesamtmenge und Nährstoffbalance erneut.', 'Complétez l’énergie avec des ingrédients adaptés tout en préservant la structure, puis revérifiez la quantité totale et l’équilibre nutritionnel.', 'Complete la energía con ingredientes adecuados manteniendo la estructura y vuelva a comprobar la cantidad total y el equilibrio nutricional.', 'Integrare l’energia con ingredienti adatti mantenendo la struttura, quindi ricontrollare quantità totale ed equilibrio nutrizionale.', '配合構成を保ちながら適切な食材でエネルギーを補い、総量と栄養バランスを再確認してください。', '배합 구조를 유지하면서 적합한 식재료로 에너지를 보충하고 총량과 영양 균형을 다시 확인하세요.'],
  ),
  DAILY_ENERGY_ADEQUATE: template(
    ['每日能量在建议范围内', 'Daily energy is within the suggested range', 'Tagesenergie liegt im empfohlenen Bereich', 'Énergie quotidienne dans la plage conseillée', 'Energía diaria dentro del intervalo recomendado', 'Energia giornaliera nell’intervallo consigliato', '1日のエネルギー量は推奨範囲内です', '일일 에너지가 권장 범위에 있습니다'],
    ['当前食谱约{total_kcal}kcal，处于建议范围{min_kcal}–{max_kcal}kcal内。', 'The recipe provides about {total_kcal} kcal, within the suggested range of {min_kcal}–{max_kcal} kcal.', 'Die Rezeptur liefert etwa {total_kcal} kcal und liegt im empfohlenen Bereich von {min_kcal}–{max_kcal} kcal.', 'La recette fournit environ {total_kcal} kcal, dans la plage conseillée de {min_kcal} à {max_kcal} kcal.', 'La receta aporta unas {total_kcal} kcal, dentro del intervalo recomendado de {min_kcal} a {max_kcal} kcal.', 'La ricetta fornisce circa {total_kcal} kcal, nell’intervallo consigliato di {min_kcal}–{max_kcal} kcal.', '現在のレシピは約{total_kcal}kcalで、推奨範囲{min_kcal}～{max_kcal}kcal内です。', '현재 레시피는 약 {total_kcal}kcal로 권장 범위 {min_kcal}~{max_kcal}kcal 안에 있습니다.'],
    ['按当前配方密度，每日总量约{suggested_grams}g，分{meals_per_day}餐喂养，并持续结合BCS和体重变化调整。', 'At the current energy density, feed about {suggested_grams} g/day over {meals_per_day} meals and continue adjusting with BCS and weight changes.', 'Bei der aktuellen Energiedichte füttern Sie etwa {suggested_grams} g/Tag auf {meals_per_day} Mahlzeiten verteilt und passen Sie die Menge anhand von BCS und Gewichtsverlauf an.', 'À la densité énergétique actuelle, donnez environ {suggested_grams} g/jour en {meals_per_day} repas et ajustez selon le BCS et l’évolution du poids.', 'Con la densidad energética actual, administre unos {suggested_grams} g/día en {meals_per_day} comidas y ajuste según el BCS y los cambios de peso.', 'Con l’attuale densità energetica, somministrare circa {suggested_grams} g/giorno in {meals_per_day} pasti e adattare in base al BCS e all’andamento del peso.', '現在のエネルギー密度では1日約{suggested_grams}gを{meals_per_day}回に分け、BCSと体重変化に応じて継続的に調整してください。', '현재 에너지 밀도에서는 하루 약 {suggested_grams}g을 {meals_per_day}회로 나누어 급여하고 BCS와 체중 변화에 따라 계속 조정하세요.'],
  ),
});

module.exports = {
  FRESH_CHECK_FINDING_TEMPLATES,
  SUPPORTED_LOCALES,
};
