const commonTimestamps = {
  created_at: { type: 'datetime', required: true, notes: '创建时间' },
  updated_at: { type: 'datetime', required: true, notes: '最后更新时间' },
};

const softDeleteField = {
  deleted_at: { type: 'datetime', required: false, nullable: true, notes: '软删除时间' },
};

const schemaBlueprint = {
  users: {
    description: 'Heybo 用户主账号。Tuya、微信、Apple 等登录身份只作为外部身份映射。',
    ownerService: 'account_service',
    primaryKey: 'id',
    fields: {
      id: { type: 'string', required: true, example: 'usr_xxx' },
      display_name: { type: 'string', required: true },
      avatar_url: { type: 'string', required: false },
      primary_phone: { type: 'string', required: false, pii: true },
      primary_email: { type: 'string', required: false, pii: true },
      country_code: { type: 'string', required: true, example: '86' },
      region: { type: 'string', required: true, example: 'CN' },
      language: { type: 'string', required: true, example: 'zh' },
      timezone: { type: 'string', required: true, example: 'Asia/Shanghai' },
      status: { type: 'enum', required: true, values: ['active', 'suspended', 'deleted'] },
      last_login_at: { type: 'datetime', required: false },
      ...commonTimestamps,
      ...softDeleteField,
    },
    indexes: ['primary_phone', 'primary_email', 'status', 'created_at'],
  },
  user_identities: {
    description: '一个用户可绑定多个登录身份，生产环境以哈希字段作为查询索引。',
    ownerService: 'account_service',
    primaryKey: 'id',
    fields: {
      id: { type: 'string', required: true, example: 'idt_xxx' },
      user_id: { type: 'string', required: true, references: 'users.id' },
      provider: { type: 'enum', required: true, values: ['phone', 'email', 'wechat', 'apple', 'google'] },
      provider_user_id: { type: 'string', required: true, pii: true },
      login_hash: { type: 'string', required: true },
      phone_country_code: { type: 'string', required: false },
      is_primary: { type: 'boolean', required: true },
      verified_at: { type: 'datetime', required: false },
      created_at: { type: 'datetime', required: true },
    },
    indexes: ['user_id', 'provider_provider_user_id_unique', 'provider_login_hash_unique'],
  },
  households: {
    description: '家庭/空间。宠物、设备、订单、记录都归属于家庭。',
    ownerService: 'household_service',
    primaryKey: 'id',
    fields: {
      id: { type: 'string', required: true, example: 'hhd_xxx' },
      name: { type: 'string', required: true },
      owner_user_id: { type: 'string', required: true, references: 'users.id' },
      region: { type: 'string', required: true, example: 'CN' },
      address_id: { type: 'string', required: false },
      ...commonTimestamps,
    },
    indexes: ['owner_user_id', 'region'],
    relatedTables: ['household_members'],
  },
  pets: {
    description: '宠物基础档案。动态健康变化进入 health_records / medical_records。',
    ownerService: 'pet_profile_service',
    primaryKey: 'id',
    fields: {
      id: { type: 'string', required: true, example: 'pet_xxx' },
      household_id: { type: 'string', required: true, references: 'households.id' },
      owner_user_id: { type: 'string', required: true, references: 'users.id' },
      name: { type: 'string', required: true },
      species: { type: 'enum', required: true, values: ['dog', 'cat'] },
      breed: { type: 'string', required: false },
      sex: { type: 'enum', required: false, values: ['male', 'female', 'unknown'] },
      neutered: { type: 'boolean', required: true },
      birth_date: { type: 'date', required: false },
      age_months: { type: 'number', required: false },
      current_weight_kg: { type: 'number', required: false },
      target_weight_kg: { type: 'number', required: false },
      body_condition_score: { type: 'string', required: false },
      activity_level: { type: 'enum', required: true, values: ['low', 'medium', 'high', 'working'] },
      life_stage: { type: 'enum', required: true, values: ['puppy', 'adult', 'senior'] },
      allergens: { type: 'json_array', required: true },
      food_restrictions: { type: 'json_array', required: true },
      health_tags: { type: 'json_array', required: true },
      doctor_notes: { type: 'text', required: false },
      user_notes: { type: 'text', required: false },
      avatar_url: { type: 'string', required: false },
      feeding_goal: { type: 'enum', required: false, values: ['maintenance', 'weight_loss', 'muscle_gain', 'post_surgery_recovery', 'coat_care', 'gastrointestinal_care'] },
      body_size: { type: 'enum', required: false, values: ['mini', 'small', 'medium', 'large', 'giant'] },
      environment: { type: 'enum', required: false, values: ['indoor', 'outdoor', 'mixed'] },
      allergy_symptoms: { type: 'json_array', required: true },
      allergy_severity: { type: 'enum', required: false, values: ['mild', 'moderate', 'severe'] },
      special_period: { type: 'enum', required: false, values: ['pregnancy', 'lactation', 'post_op_rest', 'illness_recovery'] },
      ...commonTimestamps,
      ...softDeleteField,
    },
    indexes: ['household_id', 'owner_user_id', 'species', 'life_stage'],
  },
  devices: {
    description: 'Heybo 家庭下的设备绑定关系，外部设备能力由 Tuya 映射驱动。',
    ownerService: 'device_service',
    primaryKey: 'id',
    fields: {
      id: { type: 'string', required: true, example: 'dev_xxx' },
      household_id: { type: 'string', required: true, references: 'households.id' },
      owner_user_id: { type: 'string', required: true, references: 'users.id' },
      tuya_device_id: { type: 'string', required: true },
      tuya_home_id: { type: 'string', required: false },
      tuya_pid: { type: 'string', required: false },
      mac_address: { type: 'string', required: false, example: 'AA:BB:CC:DD:EE:FF' },
      product_type: { type: 'enum', required: true, values: ['pet_chef'] },
      device_name: { type: 'string', required: true },
      status: { type: 'enum', required: true, values: ['active', 'offline', 'unbound', 'disabled'] },
      firmware_version: { type: 'string', required: false },
      last_online_at: { type: 'datetime', required: false },
      bound_at: { type: 'datetime', required: true },
      unbound_at: { type: 'datetime', required: false },
      ...commonTimestamps,
    },
    indexes: ['household_id', 'tuya_device_id_unique', 'status'],
    relatedTables: ['device_pet_bindings'],
  },
  recipes: {
    description: '可推荐和可执行的标准食谱。',
    ownerService: 'recipe_service',
    primaryKey: 'id',
    fields: {
      id: { type: 'string', required: true, example: 'rcp_xxx' },
      name: { type: 'string', required: true },
      species: { type: 'enum', required: true, values: ['dog', 'cat'] },
      category: { type: 'string', required: true },
      life_stage: { type: 'string', required: false },
      health_tags: { type: 'json_array', required: true },
      ingredients: { type: 'json_array', required: true },
      nutrition_snapshot: { type: 'json_object', required: false },
      cooking_profile: { type: 'json_object', required: true },
      source_id: { type: 'string', required: false, references: 'recipe_sources.id' },
      status: { type: 'enum', required: true, values: ['draft', 'active', 'archived'] },
      version: { type: 'number', required: true },
      ...commonTimestamps,
    },
    indexes: ['species', 'category', 'status', 'source_id'],
  },
  recipe_sources: {
    description: '食谱来源、审核和版权/溯源信息。',
    ownerService: 'recipe_service',
    primaryKey: 'id',
    fields: {
      id: { type: 'string', required: true, example: 'src_xxx' },
      source_type: { type: 'enum', required: true, values: ['manual', 'nutritionist', 'ai', 'imported'] },
      title: { type: 'string', required: true },
      author: { type: 'string', required: false },
      reference_url: { type: 'string', required: false },
      license: { type: 'string', required: false },
      reviewed_by: { type: 'string', required: false, references: 'admin_users.id' },
      reviewed_at: { type: 'datetime', required: false },
      notes: { type: 'text', required: false },
      ...commonTimestamps,
    },
    indexes: ['source_type', 'reviewed_by'],
  },
  cooking_operations: {
    description: '一次设备烹饪操作，替代当前 JSON MVP 的 device_operation_records。',
    ownerService: 'cooking_operation_service',
    primaryKey: 'id',
    fields: {
      id: { type: 'string', required: true, example: 'cop_xxx' },
      user_id: { type: 'string', required: true, references: 'users.id' },
      household_id: { type: 'string', required: true, references: 'households.id' },
      pet_id: { type: 'string', required: false, references: 'pets.id' },
      device_id: { type: 'string', required: false, references: 'devices.id' },
      recipe_id: { type: 'string', required: false, references: 'recipes.id' },
      session_id: { type: 'string', required: true },
      client_event_id: { type: 'string', required: true },
      operation_type: { type: 'enum', required: true, values: ['start_cooking', 'pause', 'resume', 'cancel', 'complete', 'stop', 'simulate'] },
      status: { type: 'enum', required: true, values: ['created', 'running', 'paused', 'completed', 'failed', 'cancelled'] },
      total_weight_g: { type: 'number', required: false },
      ingredients_snapshot: { type: 'json_array', required: false },
      cooking_params_snapshot: { type: 'json_object', required: false },
      tuya_command_snapshot: { type: 'json_object', required: false },
      result: { type: 'string', required: false },
      error_code: { type: 'string', required: false },
      event_at: { type: 'datetime', required: true },
      started_at: { type: 'datetime', required: false },
      completed_at: { type: 'datetime', required: false },
      created_at: { type: 'datetime', required: true },
    },
    indexes: ['household_id', 'pet_id', 'device_id', 'recipe_id', 'status', 'created_at'],
  },
  feeding_records: {
    description: '宠物喂食记录，可由烹饪完成自动生成或用户手动补录。',
    ownerService: 'feeding_service',
    primaryKey: 'id',
    fields: {
      id: { type: 'string', required: true, example: 'fee_xxx' },
      user_id: { type: 'string', required: true, references: 'users.id' },
      household_id: { type: 'string', required: true, references: 'households.id' },
      pet_id: { type: 'string', required: true, references: 'pets.id' },
      recipe_id: { type: 'string', required: false, references: 'recipes.id' },
      cooking_operation_id: { type: 'string', required: false, references: 'cooking_operations.id' },
      session_id: { type: 'string', required: false },
      client_event_id: { type: 'string', required: true },
      fed_at: { type: 'datetime', required: true },
      amount_g: { type: 'number', required: false },
      meal_type: { type: 'enum', required: false, values: ['breakfast', 'lunch', 'dinner', 'snack'] },
      appetite_score: { type: 'number', required: false },
      palatability: { type: 'string', required: false },
      stool_status: { type: 'string', required: false },
      notes: { type: 'text', required: false },
      created_at: { type: 'datetime', required: true },
    },
    indexes: ['household_id', 'pet_id', 'fed_at'],
  },
  health_records: {
    description: '非医疗诊断性质的日常健康观察。',
    ownerService: 'health_service',
    primaryKey: 'id',
    fields: {
      id: { type: 'string', required: true, example: 'hea_xxx' },
      user_id: { type: 'string', required: true, references: 'users.id' },
      household_id: { type: 'string', required: true, references: 'households.id' },
      pet_id: { type: 'string', required: true, references: 'pets.id' },
      recorded_at: { type: 'datetime', required: true },
      weight_kg: { type: 'number', required: false },
      stool_score: { type: 'number', required: false },
      appetite_score: { type: 'number', required: false },
      skin_coat_score: { type: 'number', required: false },
      activity_score: { type: 'number', required: false },
      symptoms: { type: 'json_array', required: false },
      notes: { type: 'text', required: false },
      created_at: { type: 'datetime', required: true },
    },
    indexes: ['household_id', 'pet_id', 'recorded_at'],
  },
  medical_records: {
    description: '体检、诊疗、疫苗、用药等医疗相关记录。',
    ownerService: 'medical_record_service',
    primaryKey: 'id',
    fields: {
      id: { type: 'string', required: true, example: 'med_xxx' },
      user_id: { type: 'string', required: true, references: 'users.id' },
      household_id: { type: 'string', required: true, references: 'households.id' },
      pet_id: { type: 'string', required: true, references: 'pets.id' },
      record_type: { type: 'enum', required: true, values: ['checkup', 'vaccine', 'medication', 'diagnosis', 'lab_result', 'other'] },
      occurred_at: { type: 'datetime', required: true },
      clinic_name: { type: 'string', required: false },
      vet_name: { type: 'string', required: false },
      summary: { type: 'text', required: true },
      attachments: { type: 'json_array', required: false },
      next_follow_up_at: { type: 'datetime', required: false },
      created_at: { type: 'datetime', required: true },
      updated_at: { type: 'datetime', required: true },
    },
    indexes: ['household_id', 'pet_id', 'record_type', 'occurred_at'],
  },
  products: {
    description: '商城商品/SPU，当前 MVP 已有轻量 seed 数据。',
    ownerService: 'commerce_service',
    primaryKey: 'id',
    fields: {
      id: { type: 'string', required: true, example: 'prd_xxx' },
      name: { type: 'string', required: true },
      category: { type: 'enum', required: true, values: ['meat_pack', 'vegetable_pack', 'nutrition_pack', 'bundle', 'device', 'service'] },
      target_tags: { type: 'json_array', required: true },
      description: { type: 'text', required: false },
      default_sku_id: { type: 'string', required: false, references: 'skus.id' },
      status: { type: 'enum', required: true, values: ['draft', 'active', 'inactive', 'archived'] },
      ...commonTimestamps,
    },
    indexes: ['category', 'status'],
  },
  skus: {
    description: '可售卖库存单元，承接价格、规格、库存和履约配置。',
    ownerService: 'commerce_service',
    primaryKey: 'id',
    fields: {
      id: { type: 'string', required: true, example: 'sku_xxx' },
      product_id: { type: 'string', required: true, references: 'products.id' },
      sku_code: { type: 'string', required: true },
      name: { type: 'string', required: true },
      spec: { type: 'json_object', required: false },
      price_cents: { type: 'number', required: true },
      currency: { type: 'string', required: true, example: 'CNY' },
      stock_status: { type: 'enum', required: true, values: ['in_stock', 'low_stock', 'out_of_stock', 'preorder'] },
      status: { type: 'enum', required: true, values: ['active', 'inactive'] },
      ...commonTimestamps,
    },
    indexes: ['product_id', 'sku_code_unique', 'status'],
  },
  orders: {
    description: '订单主表。订单项在未来迁移中拆为 order_items。',
    ownerService: 'order_service',
    primaryKey: 'id',
    fields: {
      id: { type: 'string', required: true, example: 'ord_xxx' },
      user_id: { type: 'string', required: true, references: 'users.id' },
      household_id: { type: 'string', required: true, references: 'households.id' },
      pet_id: { type: 'string', required: false, references: 'pets.id' },
      status: { type: 'enum', required: true, values: ['created', 'paid', 'fulfilling', 'shipped', 'completed', 'cancelled', 'refunded'] },
      total_cents: { type: 'number', required: true },
      currency: { type: 'string', required: true, example: 'CNY' },
      payment_status: { type: 'enum', required: true, values: ['pending', 'paid', 'failed', 'refunded'] },
      shipping_address: { type: 'json_object', required: false, pii: true },
      ...commonTimestamps,
      ...softDeleteField,
    },
    indexes: ['user_id', 'household_id', 'status', 'created_at'],
    relatedTables: ['order_items'],
  },
  payments: {
    description: '支付流水。未来接入微信支付、支付宝或 Stripe 时作为幂等和对账基础。',
    ownerService: 'payment_service',
    primaryKey: 'id',
    fields: {
      id: { type: 'string', required: true, example: 'pay_xxx' },
      order_id: { type: 'string', required: true, references: 'orders.id' },
      user_id: { type: 'string', required: true, references: 'users.id' },
      provider: { type: 'enum', required: true, values: ['wechat_pay', 'alipay', 'stripe', 'manual'] },
      provider_payment_id: { type: 'string', required: false },
      amount_cents: { type: 'number', required: true },
      currency: { type: 'string', required: true },
      status: { type: 'enum', required: true, values: ['configuration_pending', 'pending', 'authorized', 'paid', 'failed', 'cancelled', 'refunded'] },
      paid_at: { type: 'datetime', required: false },
      raw_payload: { type: 'json_object', required: false },
      ...commonTimestamps,
    },
    indexes: ['order_id', 'user_id', 'provider_payment_id', 'status'],
  },
  admin_users: {
    description: '后台运营、营养师、客服和管理员账号。',
    ownerService: 'admin_service',
    primaryKey: 'id',
    fields: {
      id: { type: 'string', required: true, example: 'adm_xxx' },
      display_name: { type: 'string', required: true },
      email: { type: 'string', required: true, pii: true },
      role: { type: 'enum', required: true, values: ['admin', 'operator', 'nutritionist', 'support', 'viewer'] },
      status: { type: 'enum', required: true, values: ['active', 'disabled'] },
      last_login_at: { type: 'datetime', required: false },
      ...commonTimestamps,
    },
    indexes: ['email_unique', 'role', 'status'],
  },
  analytics_events: {
    description: '产品分析事件，避免直接污染业务表。',
    ownerService: 'analytics_service',
    primaryKey: 'id',
    fields: {
      id: { type: 'string', required: true, example: 'evt_xxx' },
      user_id: { type: 'string', required: false, references: 'users.id' },
      household_id: { type: 'string', required: false, references: 'households.id' },
      session_id: { type: 'string', required: false },
      event_name: { type: 'string', required: true },
      event_source: { type: 'enum', required: true, values: ['app', 'backend', 'device', 'admin'] },
      properties: { type: 'json_object', required: false },
      occurred_at: { type: 'datetime', required: true },
      created_at: { type: 'datetime', required: true },
    },
    indexes: ['user_id', 'event_name', 'occurred_at'],
  },
};

const migrationNotes = {
  currentMvpStore: 'backend/src/services/heybo_store.js uses a JSON file and in-memory helpers.',
  databaseTarget: 'Use this blueprint as the contract for future relational tables or document collections.',
  namingDifferences: {
    device_operation_records: 'Rename to cooking_operations before database migration.',
    products_price_cents: 'Move sale price from products to skus; keep products as SPU.',
    order_items: 'Required companion table for orders even though it is not listed as a core exported collection.',
  },
};

module.exports = {
  schemaBlueprint,
  migrationNotes,
};
